server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sop?serverTimezone=UTC
    username: root
    password: a74898324646
  mail:
    #配置 SMTP 服务器地址
    host: smtp.qq.com
    #SMTP 服务器的端口
    port: 465
    #配置邮箱用户名
    username: 1837952922@qq.com
    #配置密码，注意，不是真正的密码，而是刚刚申请到的授权码
    password: xvhmefkutvdadfaj
    #默认的邮件编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
    #官方建议使用 465 端口，而 465 端口是 SSL 协议的，所以不仅要换端口，
    #还需要进行 SSL 协议替换。下面是在 application.properties 进行的邮件发送相关配置，
    protocol: smtp

mybatis:
  configuration:
    log-impl=org:
      apache:
        ibatis:
          logging:
            stdout:
              StdOutImpl: